namespace FSM.POCO.Console {
    using System;
    using System.Collections.Generic;

    // This part demonstrates the code generated by the FSMSource.Create method
    partial class Machine {
        readonly Internal.IDispatcher<State> dispatcher;
        public Machine() {
            var idleActions = new Dictionary<Enum, Action<object[]>>(1) {
                    { Trigger.Start, _ => OnStart() },
                };
            var fetchingActions = new Dictionary<Enum, Action<object[]>>(2) {
                    { Trigger.Success, x => OnSuccess((int)x[0]) },
                    { Trigger.Failure, x => OnFailure((Exception)x[0]) },
                };
            var errorActions = new Dictionary<Enum, Action<object[]>>(1) {
                    { Trigger.Retry, _ => OnRetry() },
                };
            var transitions = new Dictionary<State, IDictionary<Enum, Action<object[]>>>(3) { 
                { State.Idle, idleActions },
                { State.Fetching, fetchingActions },
                { State.Error, errorActions },
            };
            var settings = new Internal.DispatchersSettings<State, Trigger>();
            this.dispatcher = new Internal.Dispatcher<State>(transitions, settings);
        }
        // auto-generated enumeration
        enum Trigger {
            Start,
            Success,
            Failure,
            Retry
        }
    }
}